apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: filecoin
  version: "1.18"
  region: "us-east-1"

availabilityZones: ["us-east-1a", "us-east-1b", "us-east-1c"]

vpc:
  clusterEndpoints:
    publicAccess: true
    privateAccess: true

cloudWatch:
  clusterLogging:
    enableTypes: ["authenticator"]

iam:
  withOIDC: true

git:
  repo:
    url: "git@github.com:Digital-MOB-Filecoin/lotus-cloud-templates.git"
    branch: master
    fluxPath: "flux/"
    user: "gitops"
    email: "filecoin@users.noreply.github.com"
  operator:
    namespace: "flux"
    withHelm: true

nodeGroups:
  - name: filecoin-us-east-1a
    instanceType: i3en.2xlarge
    availabilityZones: ["us-east-1a"]
    minSize: 1
    maxSize: 3
    asgMetricsCollection:
    - granularity: "1Minute"
      metrics: ["GroupMinSize", "GroupMaxSize", "GroupDesiredCapacity", "GroupInServiceInstances", "GroupPendingInstances", "GroupStandbyInstances", "GroupTerminatingInstances", "GroupTotalInstances"]
    privateNetworking: true
    ebsOptimized: true
    volumeEncrypted: true
    volumeSize: 128
    ssh:
      allow: false
    iam:
      withAddonPolicies:
        cloudWatch: true
        ebs: true
        efs: true
    kubeletExtraConfig:
      podPidsLimit: 4194303
    preBootstrapCommands:
      - sysctl -w kernel.pid_max=4194303
    labels: 
      aws.amazon.com/eks-local-ssd: true
  - name: filecoin-us-east-1b
    instanceType: i3en.2xlarge
    availabilityZones: ["us-east-1b"]
    minSize: 1
    maxSize: 3
    asgMetricsCollection:
    - granularity: "1Minute"
      metrics: ["GroupMinSize", "GroupMaxSize", "GroupDesiredCapacity", "GroupInServiceInstances", "GroupPendingInstances", "GroupStandbyInstances", "GroupTerminatingInstances", "GroupTotalInstances"]
    privateNetworking: true
    ebsOptimized: true
    volumeEncrypted: true
    volumeSize: 128
    ssh:
      allow: false
    iam:
      withAddonPolicies:
        cloudWatch: true
        ebs: true
        efs: true
    kubeletExtraConfig:
      podPidsLimit: 4194303
    preBootstrapCommands:
      - sysctl -w kernel.pid_max=4194303
    labels: 
      aws.amazon.com/eks-local-ssd: true
  - name: filecoin-us-east-1c
    instanceType: i3en.2xlarge
    availabilityZones: ["us-east-1c"]
    minSize: 1
    maxSize: 3
    asgMetricsCollection:
    - granularity: "1Minute"
      metrics: ["GroupMinSize", "GroupMaxSize", "GroupDesiredCapacity", "GroupInServiceInstances", "GroupPendingInstances", "GroupStandbyInstances", "GroupTerminatingInstances", "GroupTotalInstances"]
    privateNetworking: true
    ebsOptimized: true
    volumeEncrypted: true
    volumeSize: 128
    ssh:
      allow: false
    iam:
      withAddonPolicies:
        cloudWatch: true
        ebs: true
        efs: true
    kubeletExtraConfig:
      podPidsLimit: 4194303
    preBootstrapCommands:
      - sysctl -w kernel.pid_max=4194303
    labels: 
      aws.amazon.com/eks-local-ssd: true
