apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: lotus-aio
  namespace: lotus-system
spec:
  releaseName: lotus-aio
  targetNamespace: lotus-system
  chart:
    git: git@github.com:Digital-MOB-Filecoin/lotus-charts
    ref: master
    path: lotus-aio
  values:
    image:
      repository: digitalmob/lotus
      tag: v1.2.1-amd64
    daemon:
      enabled: true
      init:
        importSnapshot:
          enable: true
          SNAPSHOTURL: https://fil-chain-snapshots-fallback.s3.amazonaws.com/mainnet/minimal_finality_stateroots_latest.car
        sync: true
        configFiles:
          config.toml: |
            [API]
              ListenAddress = "/ip4/127.0.0.1/tcp/1234/http"
              Timeout = "30s"
            [Libp2p]
              ListenAddresses = ["/ip4/127.0.0.1/tcp/1235", "/ip6/::1/tcp/1235"]
          resources:
            requests:
              cpu: 4000m
              memory: 32GiB
